#include <stdexcept>

int main(void){
  throw std::runtime_error("Bleh");
  return 0;
}
